apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: NodePort  # ← Change this
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30001  # Optional: fixed port
