apiVersion: v1
kind: Service
metadata:
  name: devops-end-sem-service
spec:
  type: NodePort
  selector:
    app: devops-end-sem
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 30080
