---
- name: Deploy DEVOPS-END-SEM app container
  hosts: localhost
  connection: local       # run tasks locally
  gather_facts: false    # skip the setup module (avoids sudo)
  tasks:
    - name: Pull latest image
      community.docker.docker_image:
        name: nrpatil654/devops-end-sem
        tag: latest
        source: pull

    - name: Ensure container is running
      community.docker.docker_container:
        name: devops-end-sem
        image: nrpatil654/devops-end-sem:latest
        state: started
        restart_policy: always
        ports:
          - "8080:80"


